//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LezizSofralar.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CategoryResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CategoryResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LezizSofralar.Resources.CategoryResources", typeof(CategoryResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string FieldName_Code {
            get {
                return ResourceManager.GetString("FieldName_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Sort.
        /// </summary>
        public static string FieldName_DefaultSort {
            get {
                return ResourceManager.GetString("FieldName_DefaultSort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Sort Argument Code.
        /// </summary>
        public static string FieldName_DefaultSortArgumentCode {
            get {
                return ResourceManager.GetString("FieldName_DefaultSortArgumentCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string FieldName_Description {
            get {
                return ResourceManager.GetString("FieldName_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Name.
        /// </summary>
        public static string FieldName_DisplayName {
            get {
                return ResourceManager.GetString("FieldName_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Order.
        /// </summary>
        public static string FieldName_DisplayOrder {
            get {
                return ResourceManager.GetString("FieldName_DisplayOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friendly URI.
        /// </summary>
        public static string FieldName_FriendlyURI {
            get {
                return ResourceManager.GetString("FieldName_FriendlyURI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image .
        /// </summary>
        public static string FieldName_ImagePath {
            get {
                return ResourceManager.GetString("FieldName_ImagePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Open New Page.
        /// </summary>
        public static string FieldName_IsOpenNewPage {
            get {
                return ResourceManager.GetString("FieldName_IsOpenNewPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Visible.
        /// </summary>
        public static string FieldName_IsVisible {
            get {
                return ResourceManager.GetString("FieldName_IsVisible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Visible On Mobile.
        /// </summary>
        public static string FieldName_IsVisibleOnMobile {
            get {
                return ResourceManager.GetString("FieldName_IsVisibleOnMobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meta Description.
        /// </summary>
        public static string FieldName_MetaDescription {
            get {
                return ResourceManager.GetString("FieldName_MetaDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meta Keywords.
        /// </summary>
        public static string FieldName_MetaKeywords {
            get {
                return ResourceManager.GetString("FieldName_MetaKeywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent Category.
        /// </summary>
        public static string FieldName_ParentCategoryID {
            get {
                return ResourceManager.GetString("FieldName_ParentCategoryID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Listing Page Size.
        /// </summary>
        public static string FieldName_ProductListingPageSize {
            get {
                return ResourceManager.GetString("FieldName_ProductListingPageSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short Name.
        /// </summary>
        public static string FieldName_ShortName {
            get {
                return ResourceManager.GetString("FieldName_ShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Filters.
        /// </summary>
        public static string FieldName_ShowFilters {
            get {
                return ResourceManager.GetString("FieldName_ShowFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show on Product Feed.
        /// </summary>
        public static string FieldName_ShowOnProductFeed {
            get {
                return ResourceManager.GetString("FieldName_ShowOnProductFeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show on Top Menu.
        /// </summary>
        public static string FieldName_ShowOnTopMenu {
            get {
                return ResourceManager.GetString("FieldName_ShowOnTopMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Products.
        /// </summary>
        public static string FieldName_ShowProducts {
            get {
                return ResourceManager.GetString("FieldName_ShowProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Sub Category On Top View.
        /// </summary>
        public static string FieldName_ShowSubCategoryOnTopView {
            get {
                return ResourceManager.GetString("FieldName_ShowSubCategoryOnTopView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Sub Category Products.
        /// </summary>
        public static string FieldName_ShowSubCategoryProducts {
            get {
                return ResourceManager.GetString("FieldName_ShowSubCategoryProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visibility End Date.
        /// </summary>
        public static string FieldName_VisibilityEndDate {
            get {
                return ResourceManager.GetString("FieldName_VisibilityEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visibility Start Date.
        /// </summary>
        public static string FieldName_VisibilityStartDate {
            get {
                return ResourceManager.GetString("FieldName_VisibilityStartDate", resourceCulture);
            }
        }
    }
}
